Repository EntryCNS/schoolmeal-back-ng, pull requests merged in 2022-05, with the labels that each got.

#54 🔀:: (#52) 유저 서비스 추상화
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/presentation/dto/response/SignUpResponse.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/presentation/dto/response/UserImageAcceptedDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/service/UserService.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/response/ResponseLink.java
Labels: FEAT

#62 🔀::(#61) 예외 Advice, DTO 추가
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/exception/ExceptionAdvice.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/response/ExceptionDto.java
Labels: FEAT

#60 🔀:: (#59) 메뉴 서비스 인터페이스
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/MenuRequest.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/dto/request/MenuCreationDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/dto/response/MenuStateDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/dto/response/MenucertainDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/service/MenuService.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/exception/ExceptionAdvice.java
Labels: CHORE, DOCS, FEAT, REFACTOR

#58 🔀:: (#55) 인증 서비스 작성
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/presentation/dto/request/OAuthRequestDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/service/AuthService.java
Labels: FEAT

#57 🔀::#56 Review Service 추상화
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/presentation/dto/request/WriteReviewRequestDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/presentation/dto/response/WriteReviewResponseDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/service/ReviewService.java
Labels: FEAT

#70 🔀:: (#69) UserRole을 Kotlin으로 재작성
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/type/UserRole.kt
Labels: HOTFIX

#66 🔀:: (#65) Spring Security로 JWT 인증 구현
  build.gradle
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/SchoolmealBackSetupApplication.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/service/AuthDetailsService.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/filter/JwtTokenFilter.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/security/JwtConfiguration.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/security/JwtProvider.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/security/SecurityConfiguration.java
  src/main/resources/application.properties
  src/test/java/kr/hs/dgsw/cns/schoolmealbacksetup/config/PropertiesTest.java
Labels: FEAT
