Repository EntryCNS/schoolmeal-back-ng, pull requests merged in 2022-07, with the labels that each got.

#84 🔀 :: (#83) 식단표 조회 API
  build.gradle
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/MenuController.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/dto/response/PlannerDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/service/MenuService.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/service/MenuServiceImpl.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/infra/InfraServiceConfiguration.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/infra/neis/MealPlannerInfra.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/security/SecurityConfiguration.java
  src/test/java/kr/hs/dgsw/cns/schoolmealbacksetup/controller/menu/MenuControllerTest.java
  src/test/java/kr/hs/dgsw/cns/schoolmealbacksetup/service/menu/MealPlannerInfraTest.java
Labels: FEAT

#75 🔀 :: (#52) 유저 서비스 구현
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/User.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/facade/UserFacade.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/presentation/UserController.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/presentation/dto/request/SignUpRequest.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/presentation/dto/request/UserRequestDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/presentation/dto/response/SignUpResponse.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/presentation/dto/response/UserResponseDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/service/UserService.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/service/UserServiceImpl.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/response/ResponseLink.java
  src/test/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/UserServiceTest.java
Labels: FEAT

#82 🔀:: (#81) 리뷰 서비스 및 컨트롤러 작성 (테스트 작성)
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/presentation/ReviewController.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/presentation/dto/request/WriteReviewRequestDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/presentation/dto/response/WriteReviewResponseDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/repository/ReviewRepository.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/service/ReviewService.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/service/ReviewServiceImpl.java
  src/test/java/kr/hs/dgsw/cns/schoolmealbacksetup/service/review/ReviewServiceTest.java
Labels: FEAT, REFACTOR

#89 🔀 :: (#88) 조회 시 기준 상태 추가
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/MenuRequest.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/MenuController.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/dto/request/MenuSelectionType.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/repository/MenuRequestRepository.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/service/MenuService.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/service/MenuServiceImpl.java
Labels: FEAT, HOTFIX

#91 🔀 :: (#90) 메뉴 조회 시 본인의 투표여부 추가
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/dto/response/MenuDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/service/MenuServiceImpl.java
  src/test/java/kr/hs/dgsw/cns/schoolmealbacksetup/controller/menu/MenuControllerTest.java
  src/test/java/kr/hs/dgsw/cns/schoolmealbacksetup/service/menu/MenuServiceTest.java
Labels: FEAT, HOTFIX
