Repository EntryCNS/schoolmeal-back-ng, pull requests merged in 2022-04, with the labels that each got.

#24 🔀:: (#20) 모든 메뉴 가져오기
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/dto/response/MenuDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/dto/response/MenuListDto.java
Labels: FEAT

#27 🔀:: #26 리뷰 조회 DTO 생성
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/presentation/dto/response/ReviewDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/presentation/dto/response/ReviewListDto.java
Labels: CHORE, FEAT

#29 🔀:: (#28) 메뉴 추가 dto 생성
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/dto/request/MenuCreationDto.java
Labels: FEAT

#25 🔀:: OAuth 사용자 추가
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/presentation/dto/request/SignInRequest.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/presentation/dto/response/SignInResponse.java
Labels: FEAT

#33 🔀::(#32) 리뷰 추가 dto 생성
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/dto/request/WriteReviewRequestDto.java
Labels: FEAT

#34 🔀:: (#31) 토큰 재발급 DTO
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/presentation/dto/request/TokenRefreshRequest.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/presentation/dto/response/TokenRefreshResponse.java
Labels: FEAT

#37 🔀:: (#35) 유저 조회 DTO 생성
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/presentation/dto/request/UserRequestDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/presentation/dto/response/UserResponseDto.java
Labels: FEAT

#42 🔀:: #41 메뉴 상태 설정 DTO 생성
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/dto/response/MenuSetState.java
Labels: FEAT

#40 🔀::#39 특정 메뉴 가져오기 DTO
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/dto/response/MenucertainDto.java
Labels: FEAT

#47 🔀::(#45) ORM 중 발생한 오류를 해결함
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/MenuRequest.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/VoteId.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/AuthId.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/AuthIdToken.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/User.java
Labels: HOTFIX

#44 🔀:: (#43) CI 세팅
  .github/workflows/build.yml
  build.gradle
  gradlew
Labels: SETTING, TEST

#51 🔀::(#50) global 예외 패키지 및 관련 DTO 삭제
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/exception/ExceptionAdviceHandler.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/response/dto/ExceptionResponseDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/response/service/ResponseService.java
Labels: REFACTOR

#49 🔀::(#48) 리포지토리 어노테이션 추가
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/repository/OAuthRepository.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/repository/MenuRequestRepository.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/repository/VoteRepository.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/repository/ReviewRepository.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/repository/UserRepository.java
Labels: HOTFIX

#53 🔀:: (#30) 회원가입 DTO
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/presentation/dto/request/SignUpRequest.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/presentation/dto/response/SignUpResponse.java
Labels: FEAT, HOTFIX
