Repository EntryCNS/schoolmeal-back-ng, pull requests merged in 2022-03, with the labels that each got.

#4 🔀:: #3 Domain - User 리펙토링
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/User.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/repository/UserRepository.java
Labels: REFACTOR

#2 🔀:: #1 Global exception, response 리펙토링
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/exception/ExceptionAdviceHandler.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/response/dto/ExceptionResponseDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/response/service/ResponseService.java
Labels: REFACTOR

#6 ♻️:: #5 Review-domain
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/entity/Review.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/repository/ReviewRepository.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/type/ReviewTime.kt
Labels: REFACTOR

#11 🔀:: (#10) CommonUser 엔티티
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/AuthId.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/AuthIdToken.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/CommonUser.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/repository/CommonUserRepository.java
Labels: FEAT

#15 🔀:: (#14) CommonUser 엔티티 완성
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/commonuser/entity/CommonUser.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/commonuser/repository/CommonUserRepository.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/entity/UserId.java
Labels: FEAT

#16 🔀:: (#12) Vote 엔티티 구현
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/Vote.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/VoteId.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/repository/VoteRepository.java
Labels: FEAT

#18 🔀:: (#17) 핫픽스 1차
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/VoteId.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/CommonUser.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/User.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/repository/CommonUserRepository.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/type/UserRole.java
Labels: HOTFIX

#19 🔀:: (#17) 핫픽스 2차
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/entity/OAuthUser.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/repository/OAuthRepository.java
Labels: HOTFIX

#23 🔀:: (#22) 메뉴 카테고리 필드 추가
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/MenuRequest.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/type/MenuCategory.kt
Labels: HOTFIX
