Repository EntryCNS/schoolmeal-back-ng, pull requests merged in 2022-06, with the labels that each got.

#72 🔀 :: (#63) Auth 도메인 구현
  .gitignore
  build.gradle
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/commonuser/entity/CommonUser.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/commonuser/repository/CommonUserRepository.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/entity/OAuthUser.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/presentation/AuthController.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/repository/OAuthRepository.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/service/AuthDetailsService.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/service/AuthService.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/service/AuthServiceImpl.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/User.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/repository/UserRepository.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/config/GoogleAuthConfiguration.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/exception/BusinessException.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/exception/ExceptionAdvice.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/infra/InfraServiceConfiguration.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/infra/google/GoogleApiService.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/infra/google/GoogleAuthService.java
Labels: FEAT

#79 🔀:: (#78) Authentication Principal 유효성 검증 관심사 AOP 검증 적용
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/presentation/AuthController.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/service/AuthDetailsService.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/aop/Authorized.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/aop/AuthorizedAspect.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/filter/JwtTokenFilter.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/security/JwtProvider.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/security/TokenException.java
Labels: HOTFIX

#80 🔀:: (#64) 메뉴 서비스 및 컨트롤러 구현, 테스트 작성
  .gitignore
  build.gradle
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/SchoolmealBackSetupApplication.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/presentation/AuthController.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/service/AuthServiceImpl.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/MenuRequest.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/Vote.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/VoteId.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/MenuController.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/dto/request/MenuCreationDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/dto/request/MenuStateDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/dto/response/MenuDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/dto/response/MenuStateDto.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/repository/MenuRequestRepository.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/repository/VoteRepository.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/service/MenuService.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/service/MenuServiceImpl.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/type/MenuCategory.kt
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/User.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/aop/Authorized.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/aop/AuthorizedAspect.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/filter/JwtTokenFilter.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/security/JwtProvider.java
  src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/security/SecurityConfiguration.java
  src/test/java/kr/hs/dgsw/cns/schoolmealbacksetup/controller/menu/MenuControllerTest.java
  src/test/java/kr/hs/dgsw/cns/schoolmealbacksetup/service/menu/MenuServiceTest.java
Labels: DOCS, FEAT, HOTFIX, REFACTOR, TEST
